video_capture: 0

face_detector:
  verbose: false
  pyr_down: 2   # Must be a power of 2
  face_selector:
    type: biggest_face
    confidence_threshold: 95

blink_classifier:
  eyes_cropper:
    type: separate_eyes_cropper
    x_crop_ratio: 0.8
    y_crop_ratio: 0.4
    use_manhattan_distance: true
    min_cropped_img_width: 26
    min_cropped_img_height: 13
  feature_extractor:
    type: segmentation_extractor
    xml_path: "../models/eye_unet/FP32/eye_unet_32.xml"
    bin_path: "../models/eye_unet/FP32/eye_unet_32.bin"
    dnn_backend: 0    # 0 = DNN_BACKEND_DEFAULT, 1 = DNN_BACKEND_HALIDE, 2 = DNN_BACKEND_INFERENCE_ENGINE, 3 = DNN_BACKEND_OPENCV
    input_width: 80
    input_height: 40
    input_scale_factor: 0.00392156862745098    # it is 1/255
    n_classes: 3
    class_to_return: 2  # 0=pupil, 1=white, 2=background
    visualize: true
  sequence_classifier:
    type: nn_classifier
    xml_path: "../models/seg_lstm/FP32/seg_lstm.xml"
    bin_path: "../models/seg_lstm/FP32/seg_lstm.bin"
    dnn_backend: 0    # 0 = DNN_BACKEND_DEFAULT, 1 = DNN_BACKEND_HALIDE, 2 = DNN_BACKEND_INFERENCE_ENGINE, 3 = DNN_BACKEND_OPENCV
    confidence_threshold: 95
    batch_size: 2
    sequence_length: 10
    img_feature_length: 1

