face_detector:
  verbose: false
  face_selector:
    type: biggest_face
    confidence_threshold: 95

blink_classifier:
  eyes_cropper:
    type: separate_eyes_cropper
    x_crop_ratio: 0.8
    y_crop_ratio: 0.4
    use_manhattan_distance: true
  feature_extractor:
    type: segmentation_extractor
    xml_path: "../models/eye_unet/eye_unet.xml"
    bin_path: "../models/eye_unet/eye_unet.bin"
    input_width: 80
    input_height: 40
    input_scale_factor: 0.00392156862745098    # it is 1/255
    n_classes: 3
    class_to_return: 2  # 0=pupil, 1=white, 2=background
    visualize: true
  sequence_classifier:
    type: semantic_classifier
    xml_path: "../models/seg_lstm/seg_lstm.xml"
    bin_path: "../models/seg_lstm/seg_lstm.bin"
    confidence_threshold: 95
    batch_size: 2
    sequence_length: 10
    img_feature_length: 1
    blink_class_id: 1
    seg_threshold: 0.99
    reference_class: 0

